### ISSUE TITLE
LUA Error in new Classic Era/SoD

### ISSUE THREAD

**Issue by ghost** [nebularg/BetterAddonList#7]
Message: ...AddOns/Blizzard_SharedXML/Classic/UIDropDownMenu.lua:897: attempt to index local 'frame' (a nil value)
Time: Sun Oct  6 12:13:00 2024
Count: 1
Stack: ...AddOns/Blizzard_SharedXML/Classic/UIDropDownMenu.lua:897: attempt to index local 'frame' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedXML/Classic/UIDropDownMenu.lua"]:897: in function `UIDropDownMenu_SetSelectedValue'
[string "@Interface/AddOns/BetterAddonList/BetterAddonList_Classic.lua"]:157: in function `?'
[string "@Interface/AddOns/BetterAddonList/BetterAddonList_Classic.lua"]:43: in function <...e/AddOns/BetterAddonList/BetterAddonList_Classic.lua:43>

Locals:

**Comment by medlir** [comment]
Retail seems to have this line `UIDropDownMenu_SetSelectedValue(AddonCharacterDropDown, character)` commented out, but also wrapped in an if statement.  Changing it in the classic code on line 157 of `BetterAddonList_Classic.lua` to be:
```
if AddonCharacterDropDown then 
    AddonUIDropDownMenu_SetSelectedValue(AddonCharacterDropDown, character)
end
```
Seems to allow it to work essentially normally, other than the the loss of the top-left character list dropdown in the panel being set to All rather than your character.

**Comment by nebularg** [comment]
Should be fixed now, thanks
