### ISSUE TITLE
Problems with characters with the same name on different Realms

### ISSUE THREAD

**Issue by Starfighter7201** [nebularg/BetterAddonList#9]
I think this addon might have an issue when trying to load sets of addons on character of which you also have one with the exact same name and class on another realm. I have now experience this twice. Once with 2 DH's and another time with 2 Druids. I'm not 100% sure it's this addon causing it, but I assume it is, since you can still enable and disable addons individually.

**Comment by nebularg** [comment]
You'll have to be more specific about what your issue is 😝 

Sets are stored account-wide, but the actual addon state (what is enabled/disabled) is per character and completely separate from addon settings.

I can only think of a few things that would change addons across multiple characters: if the dropdown in the top left is "All" instead of your character name, if they are a new character, or if you've installed/removed a bunch of addons (the game has had issues in the past when a character was missing addon state entries, the merge logic would result in weird things seemingly linked to their "All" setting)

**Comment by nebularg** [comment]
So I created another char with the same name on another server and I see what you mean: enabling/disabling just seems to not work at all.
